events {
    worker_connections 1024;
}

http {
    upstream backend {
        server 172.19.0.2:50;
        server 172.19.0.3:50;
        server 172.19.0.4:50;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
        }
    }
}
